### PR TITLE
Added multiple ICAO codes input, added test for multiple ICAO codes

### LINKED ISSUE #282: 🚀 Feature: CLI option to allow multiple ICAO codes at the same time
### 🔖 Feature description

Should allow the ability to save multiple charts at the same time by passing commas separated ICAO codes like,

```sh
$ node app/main.js --icao VABB,KJFK
```

### 🎤 Pitch

Will allow the ability to scrape multiple but specific ICAO codes in a single command.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar feature request

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by PrBart**
# Description

Added multiple ICAO codes input, added test for multiple ICAO codes

Fixes #282

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Test A
- [x] Test B
But several test failed due to incorrect data in csv or airports.json.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation/readme
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by drph4nt0m** [comment]
Hey @PrBart, you made changes to how the getAirport works. I would prefer if the getAirport remains the same and you just iterate in the main and call it multiple times. It won't be a big efficiency concern because I will be only using this command when running for 5-10 airports.

**Comment by PrBart** [comment]
> Hey @PrBart, you made changes to how the getAirport works. I would prefer if the getAirport remains the same and you just iterate in the main and call it multiple times. It won't be a big efficiency concern because I will be only using this command when running for 5-10 airports.

In my mind making several loops in a main function is not the best way how to make good readable and easy to maintain code.
I think sooner or later you will have to come to solution like that.

**Comment by PrBart** [comment]
Ok, it's seems i really have broken the tests.

Sorry, used to work with TS, so didn't expect behavior this kind.

**Comment by PrBart** [comment]
> @PrBart if you can, please create one more PR and update the `skip-countries` option to also use the `commaSeparatedList()`.

Ok, i will.
You can create an issue and assign me to it.

**Comment by drph4nt0m** [comment]
@PrBart created the issue https://github.com/drph4nt0m/avbot-charts/issues/327. Comment on it and I will assign it to you.

**Pull request merged**
