### PR TITLE
Logging in different files

### LINKED ISSUE #317: 🚀 Feature: Distributed log files
### 🔖 Feature description

This feature is only for saving logs to files. The winston logging on console should work as it currently does.

Split the logs for each run into multiple files. For example, the log files created when ran `node ./app/main.js -c IN,US` would be

- `logs/<timestamp_of_program_run>.log`
- `logs/<timestamp_of_program_run>_IN.log`
- `logs/<timestamp_of_program_run>_US.log`

`timestamp_of_program_run` will be same for all 3 files and it will be set once the program is started.

### 🎤 Pitch

Currently the winston logs everything to one log file per run. It would be great if the log file can be further split based countries for each run. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/drph4nt0m/avbot-charts/blob/HEAD/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by koshimagoyal**
# Description

Had made changes in logger.js,main.js and getCharts.js to split logs based on country at runtime. 

Fixes #317 

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] made changes in run script of package.json. Changed  "node app/main.js" to "node app/main.js -c IN,US"

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation/readme
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by drph4nt0m** [comment]
@koshimagoyal i like what you did but you have changed the whole logging. I would like the old logger style but just the extra feature of the country logs going to separate files.

**Comment by koshimagoyal** [comment]
hi @drph4nt0m 
I am not clear with requirement. Can you please elaborate? Console logging is working as earlier and I only made changes for file level. Normal file will have all logs except country logs and country files will have their country logs.

**Comment by drph4nt0m** [comment]
Yeah. That is what the requirements are. But you made a lot of extra changes to the logger which is not required. Also you changed the logger.info/error calls logger.log which is not what I want.

I would prefer something more simple like same logger file but just having one more parameter passed (similar to type) in the second argument object. And that will have the country code. If no code is passed, it should default to the misc log.

**Comment by koshimagoyal** [comment]
It is not possible you cant create files dynamically and start logging into that. Currently winston not support this feature - https://stackoverflow.com/questions/51547294/how-to-create-multiple-log-files-and-append-logs-in-that-file-using-winston-libr
This is possible only by changing logging levels.

**Comment by drph4nt0m** [comment]
Then how many levels will you have? I mean if you are saving that the only way possible is with the levels, then you need to have separate levels for all the countries?

**Comment by koshimagoyal** [comment]
Yes we will have to make one level for each country and if no country is provided then no extra level is required.

**Comment by drph4nt0m** [comment]
@koshimagoyal I am sorry but I really don't want this implemention. If you can come up with something much cleaner, I will merge it. Otherwise let me know and I am just close it and add `hacktoberfest-accepted` label.

**Comment by koshimagoyal** [comment]
Ok @drph4nt0m you can take relevant action.

**Comment by drph4nt0m** [comment]
@koshimagoyal thanks for your contribution. 🚀

**Pull request closed without merging**
